AWSTemplateFormatVersion: '2010-09-09'
Description: Step 1 - Uniquely named S3 bucket for movie data using account ID and region

Resources:
  WorkshopS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "movie-data-bucket-${AWS::AccountId}-${AWS::Region}"
    DeletionPolicy: Delete

Outputs:
  BucketName:
    Description: "Name of the S3 bucket created for movie data"
    Value: !Ref WorkshopS3Bucket
